version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      time: "06:00"
      day: "monday"
      timezone: "America/Argentina/Cordoba"
    allow:
      # Only check production packages
      - dependency-type: "production"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/client"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      time: "06:00"
      day: "monday"
      timezone: "America/Argentina/Cordoba"
    allow:
      # Only check production packages
      - dependency-type: "production"
